M48
; DRILL file {KiCad 7.0.10-7.0.10~ubuntu22.04.1} date mar 30 ene 2024 11:01:20
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-30T11:01:20+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-7.0.10~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X20.551Y-21.518
X28.551Y-21.518
T2
X15.0Y-15.0
X15.0Y-154.0
X33.5Y-15.0
X33.5Y-154.0
M30
